name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  supabase_flutter: ^2.15.0
  crypto: ^3.0.7
  crypt: ^4.3.1
  image_picker: ^1.2.2
  google_sign_in: ^7.2.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.3.0
  webview_flutter: ^4.14.0 # ⬅️ Nos quedamos con el oficial de Google
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

# Configuración del Splash apuntando al nuevo PNG de alta resolución
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Light.png
  android_gravity: center
  ios_content_mode: center

  # Forza a Android 12+ a usar el nuevo logo nítido
  android_12:
    image: assets/Light.png
    color: "#FFFFFF"

# Configuración para cambiar el logo exterior de la App
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/SVG.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Rutas de recursos alineadas perfectamente con tu árbol de carpetas (¡Todo completo!)
  assets:
    - assets/images/undraw_mobile-application_uc2q.svg
    - assets/images/business.png
    - assets/Light.png
    - assets/SVG.png
    - assets/captcha.html